### ISSUE TITLE
Azure tags on backend storage not respected due to camelize the request

### ISSUE THREAD

**Issue by HoLengZai** [boltops-tools/armrest#2]
Hi,
Any particular reason that you set `camelize(data)` at line 67?
As I got an issue to set Azure Tags as it does not respect the case sensitivity and underscore for my azure backend tags
So as a workaround, I removed the line 67 on my local development machine and it works as expected
Thanks

https://github.com/boltops-tools/armrest/blob/3bb38d3466556a7b77c6786fd252de02da533e10/lib/armrest/api/base.rb#L65-L71

**Comment by tongueroo** [comment]
The link above points to an old code version 🤔 The camelize was removed by https://github.com/boltops-tools/armrest/pull/1 Reasons are also detailed in https://community.boltops.com/t/tag-name-key-is-converted-to-lowercase/868/3?u=tung

Upgrade to remove the camelize. In the terraspace project 

    bundle update
