### ISSUE TITLE
Armrest v0.1.3 CLI Auth is now not working anymore

### ISSUE THREAD

**Issue by RiddlerKnight** [boltops-tools/armrest#3]
Reproduce:
```
az login -u xxx -p xxx     # output account detail in json
armrest auth               # output Unable to authenticate
armrest auth msi           # output Unable to authenticate
armrest auth cli           # output Unable to authenticate
```

Testing Environment:
os: wsl ubuntu 20.04
version: armrest v0.1.3

I'm a newbie in ruby. I try to debug with vscode on windows but It's quite difficult cuz there are some issue with devkit.

**Comment by raquel11111** [comment]
Yes

**Comment by RiddlerKnight** [comment]
According to ms doc, accessTokens.json is deprecated
https://learn.microsoft.com/en-us/cli/azure/msal-based-azure-cli

This line won't work anymore.
https://github.com/boltops-tools/armrest/blob/c9e735551dee7d6d4b7999b1beb47c6b1cec122f/lib/armrest/auth.rb#L44

**Comment by tongueroo** [comment]
Oh I see. That helps and explains it 👍 Can get rid of that line and check if the cli auth simply was able to return a token from the `az account get-access-token` call. Will take a look, but unsure when. Will also consider PRs. Thanks. 

When you get a chance try

    cd your-terraspace-project 
    bundle info armrest

That’ll tell you where armrest is located. Then open up the file and comment out the line to test. On the road.

**Comment by tongueroo** [comment]
For posterity [HTTPUnauthorized Community Post](https://community.boltops.com/t/httpunauthorized/1113/5)

**Comment by syepes** [comment]
Effectively this is the issue: https://learn.microsoft.com/en-us/cli/azure/msal-based-azure-cli#accesstokensjson-deprecation
If I user the cmd `az account get-access-token` I get the JSON

**Comment by syepes** [comment]
Looks like `k.underscore` is not working @tongueroo do you know whats going on?
https://github.com/boltops-tools/armrest/pull/4/files#diff-3d3be3f766e01cb6a2d4faaee6a692c7f674660ed85561542e1b57d3c7bc7086R24

Fixed in the last commit ;-)
